import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'
import pg from 'pg'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '../..')
const jsonPath = path.join(root, 'backend/database/schema/public-columns.json')
const tsPath = path.join(root, 'frontend/web/src/lib/dbSchema.generated.ts')

function getDatabaseUrl() {
  if (process.env.DATABASE_URL) return process.env.DATABASE_URL
  const json = execSync('railway variables --service Postgres-MC1Y --json', {
    encoding: 'utf8',
    cwd: root,
  })
  const vars = JSON.parse(json)
  return (
    vars.POSTGRES_URL ||
    vars.DATABASE_URL ||
    vars.POSTGRES_PRIVATE_URL ||
    vars.DATABASE_PRIVATE_URL ||
    vars.DATABASE_PUBLIC_URL
  )
}

const url = getDatabaseUrl()
if (!url) {
  console.error('DATABASE_URL not found')
  process.exit(1)
}

async function connect() {
  const attempts = [
    { connectionString: url, ssl: false },
    { connectionString: url, ssl: { rejectUnauthorized: false } },
    {
      connectionString: url.includes('sslmode=')
        ? url
        : `${url}${url.includes('?') ? '&' : '?'}sslmode=require`,
      ssl: { rejectUnauthorized: false },
    },
  ]
  let lastErr
  for (const cfg of attempts) {
    const c = new pg.Client(cfg)
    try {
      await c.connect()
      return c
    } catch (err) {
      lastErr = err
      try {
        await c.end()
      } catch {
        /* ignore */
      }
    }
  }
  throw lastErr
}

const COLUMNS_SQL = `
  SELECT table_name, column_name, data_type, is_nullable, ordinal_position
  FROM information_schema.columns
  WHERE table_schema = 'public'
  ORDER BY table_name, ordinal_position
`

function writeGenerated(rows) {
  const publicColumns = {}
  const publicTables = []
  for (const row of rows) {
    if (!publicColumns[row.table_name]) {
      publicColumns[row.table_name] = []
      publicTables.push(row.table_name)
    }
    publicColumns[row.table_name].push(row.column_name)
  }
  const body = `/* Generated by npm run db:dump-schema. Do not edit by hand. */\nexport const publicTables = ${JSON.stringify(publicTables, null, 2)} as const\n\nexport const publicColumns = ${JSON.stringify(publicColumns, null, 2)} as const\n`
  fs.writeFileSync(tsPath, body)
}

try {
  const client = await connect()
  try {
    await client.query("SET statement_timeout = '30s'")
    const result = await client.query(COLUMNS_SQL)
    const rows = result.rows.map((row) => ({
      table_name: row.table_name,
      column_name: row.column_name,
      data_type: row.data_type,
      is_nullable: row.is_nullable,
      ordinal_position: Number(row.ordinal_position),
    }))
    fs.mkdirSync(path.dirname(jsonPath), { recursive: true })
    fs.writeFileSync(jsonPath, `${JSON.stringify(rows, null, 2)}\n`)
    writeGenerated(rows)
    const tables = new Set(rows.map((row) => row.table_name))
    console.log(`${rows.length} columns, ${tables.size} tables`)
  } finally {
    await client.end()
  }
} catch {
  console.error('Schema query failed')
  process.exit(1)
}
